productName = "vizjj"
version = "0.1.0"
identifier = "natural.selection.vizjj"

[build]
beforeDevCommand = "bun run dev"
devUrl = "http://localhost:5133"
beforeBuildCommand = "bun run build"
frontendDist = "../dist"


[app]
[[app.windows]]
label = "main"
title = "vizjj"
width = 800
height = 600
resizable = true
focus = true
decorations = false

[bundle]
# active = true # Comment this out or set to false to disable bundle compilation
targets = "all"
icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico",
]

[app.security]
# csp = null
